### PR TITLE
fix: capture render tree can fail if args cannot be obtained

### PR DESCRIPTION
**Pull request by patricklx**
this currently happens on https://meta.discourse.org/ when checking with ember-inspector and not being logged in.

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
hello! can a test be added? thanks!

**Comment by patricklx** [comment]
Hi, where can I add that?

**Comment by NullVoxPopuli** [comment]
maybe in here? https://github.com/glimmerjs/glimmer-vm/blob/master/packages/%40glimmer-workspace/integration-tests/test/debug-render-tree-test.ts

**Comment by patricklx** [comment]
added the tests for this.
Could this also be backported?

**Comment by patricklx** [comment]
@NullVoxPopuli

**Comment by NullVoxPopuli** [comment]
unsure, what version would you want to backport to?

**Review by NullVoxPopuli — APPROVED** [review]

**Comment by NullVoxPopuli** [comment]
for  others, a repro of the problem: https://stackblitz.com/edit/github-pgxsyq?file=app%2Fcomponents%2Fwelcome.gts

(open the ember inspector, ensure the `throw` is happening, and see that the component view is blank)

**Comment by NullVoxPopuli** [comment]
glimmer-vm doesn't have an LTS tho :sweat_smile: 

an issue is that even if we fix ember-LTS, all the versions in between won't be fixed, because glimmer-vm is bundled with ember-source right now.

**Comment by patricklx** [comment]
i think we need to revert this.
it affects also other parts of glimmer...

**Comment by NullVoxPopuli** [comment]
How do you mean? Can we add more tests to prevent whatever it in you've discovered?

**Comment by NullVoxPopuli** [comment]
Looks like #1460 expnains

**Comment by patricklx** [comment]
for example here it is used: https://github.com/glimmerjs/glimmer-vm/blob/master/packages/%40glimmer/runtime/lib/helpers/fn.ts#L87.
in application this change would have caught errors, and the developer would not see it in the app...

**Comment by NullVoxPopuli** [comment]
Oofta, that tells me we don't have sufficient failure-case testing

**Pull request merged**
