### PR TITLE
Preserve original comment style when available

### PR DESCRIPTION
**Pull request by mmun**
Addresses @rwjblue's [comment](https://github.com/tildeio/glimmer/pull/382#discussion_r95986330) in #382.

This PR is a bit gnarly because I had to string the `source` through each function. We should rewrite these functions as a methods on a class [like these guys](https://github.com/tildeio/glimmer/blob/master/packages/@glimmer/syntax/lib/parser.ts#L62-L101).

### CODE REVIEW

**Comment by sclaxton** [comment]
Hmm why can't we just add a `isSafeComment` flag to the `MustacheComment` AST node so that we preserve this information in the AST?

**Comment by mmun** [comment]
Because it is irrelevant to the semantics of the template, which is what the Abstract Syntax Tree is supposed to capture. For the same reason, we don't capture whitespace into the AST, whether you use `{{^}}` or `{{else}}`, etc.

**Comment by krisselden** [comment]
@mmun do you need to rebase?

**Comment by mmun** [comment]
Will do.

**Comment by Turbo87** [comment]
closing due to inactivity and conflicts

**Pull request closed without merging**
