### PR TITLE
Remove obsolete BREAKING.md file

### PR DESCRIPTION
**Pull request by Turbo87**
It is unclear what this document is describing and what version it belongs to so we might as well delete it.

### CODE REVIEW

**Comment by rwjblue** [comment]
I think it was an attempt to explain the breaking changes (generally speaking) landed between 0.38 and 0.40(ish), but @wycats / @tomdale would have to confirm.

**Comment by Turbo87** [comment]
then we should move it to the changelog IMHO

**Comment by rwjblue** [comment]
Has conflicts ATM, but happy to merge if you update @Turbo87 (sorry)

**Comment by Turbo87** [comment]
done :)

**Pull request merged**
