### PR TITLE
[Improvement] prefer for cloneNode instead of createElement

### PR DESCRIPTION
**Pull request by lifeart**
https://jsperf.com/clonenode-vs-createelement-performance/32

### CODE REVIEW

**Comment by rwjblue** [comment]
Looks like current CI failure is due to types (you can replicate locally via `yarn run problems`):

```
$ yarn run problems
yarn run v0.27.5
$ tsc -p tsconfig.json --noEmit
packages/@glimmer/node/lib/node-dom-helper.ts(27,24): error TS2339: Property 'nodesCache' does not exist on type 'Document'.
packages/@glimmer/node/lib/node-dom-helper.ts(28,21): error TS2339: Property 'nodesCache' does not exist on type 'Document'.
packages/@glimmer/node/lib/node-dom-helper.ts(30,19): error TS2339: Property 'nodesCache' does not exist on type 'Document'.
packages/@glimmer/node/lib/node-dom-helper.ts(35,26): error TS2339: Property 'nodesCache' does not exist on type 'Document'.
packages/@glimmer/node/lib/node-dom-helper.ts(35,54): error TS2339: Property 'nodesCache' does not exist on type 'Document'.
packages/@glimmer/node/lib/node-dom-helper.ts(39,26): error TS2339: Property 'nodesCache' does not exist on type 'Document'.
error Command failed with exit code 1.
```

**Comment by rwjblue** [comment]
Also, we probably will want to run some macro benchmarks against this to see what impact it has (positive or negative).

**Comment by lifeart** [comment]
https://jsperf.com/createelement-vs-clonenode-fragment-cache

**Comment by rwjblue** [comment]
Definitely appreciate the micro benchmark, but we will need to test this in a macro benchmark also before we can land it. In other words, we need to see how this affects real apps in addition to these sorts of tightly constrained micro benchmark scenarios.

**Comment by tomdale** [comment]
I don't think this approach ends up being faster. The microbenchmark does not capture certain aspects of real-world behavior, and given how close the two are (node cache version is ~5% faster on my machine), I wouldn't be surprised if it is actually slower, for these reasons:

1. The microbenchmark does not include the `hasOwnProperty` check to see if the node is already in the dictionary.
2. The microbenchmark does not use a large enough variety of HTML element types to defeat some optimizations that are probably happening here, e.g. putting the node cache into dictionary mode, functions becoming megamorphic, etc.

When a microbenchmark shows me something surprising, I always try to find an explanation for the difference, because of how difficult it is to construct representative synthetic benchmarks. (I even [wrote a blog post about it](https://tomdale.net/2017/07/adventures-in-microbenchmarking/).

In this case, the question I ask myself is: if using `cloneNode(false)` for creating a new, empty element is faster, why would the browser not use this path itself? The performance of `document.createElement()` is definitely in the hot path of many of the browser benchmarks, so why would this not have been optimized?

**Comment by tomdale** [comment]
Gonna close this until we have better benchmarks. Thank you for the PR!

**Pull request closed without merging**
