### PR TITLE
Switch from Saucelabs to Browserstack

### PR DESCRIPTION
**Pull request by kategengler**
~Waiting on confirmation of Open Source account.~ ~BrowserStack has assured me the Open Source license will be activated when the logo credit to them is in the README (included in this PR).~ BrowserStack account is activated.

Of note: 
- Sadly, there is no way to indicate `latest - 1` as a version in BrowserStack, so these browser versions will need to be periodically updated.

### CODE REVIEW

**Comment by rwjblue** [comment]
> Ember.js uses a failure-only reporter to reduce output, if desired we can extract that and use it here as well.

Yeah, I guess that means we should extract to a separate package that we can share as needed, right?

**Comment by kategengler** [comment]
Yes, I can do that if that's desired. (vs. having to click to the plain-text log)

**Comment by kategengler** [comment]
The extracted failure-only reporter works -- just need to figure out publishing it before this is ready.

**Comment by rwjblue** [comment]
Eeck. Just made a yarn.lock conflict here, sorry.

**Comment by kategengler** [comment]
Published `testem-failure-only-reporter` -- I think this PR is now ready?

**Pull request merged**
