### PR TITLE
yarn.lock: Deduplicate dependency versions

### PR DESCRIPTION
**Pull request by Turbo87**
see https://github.com/atlassian/yarn-deduplicate

### CODE REVIEW

**Comment by Turbo87** [comment]
I guess it's not a good sign that this just freezed on `ember build` now........ 😱

**Comment by rwjblue** [comment]
No, definitely not great...

**Comment by rwjblue** [comment]
Any insight on why this is getting stuck?

**Comment by Turbo87** [comment]
no, haven't looked into it yet

**Comment by Turbo87** [comment]
I've narrowed it down to `broccoli-babel-transpiler@6.4.0` being the first bad release

/cc @stefanpenner

**Comment by Turbo87** [comment]
I've excluded the Babel dedupes from this PR for now to make it work, but this remains a problem...

**Comment by rwjblue** [comment]
Also might try adding `JOBS=1` to ensure we aren't just doing parallelization when we didn't mean too...

**Comment by Turbo87** [comment]
@rwjblue it might also be Babel itself updating because the package depending on Babel is updated 🤷‍♂️

**Pull request merged**
