### PR TITLE
ast-node-cache

### PR DESCRIPTION
**Pull request by lifeart**
checking https://github.com/glimmerjs/glimmer-vm/pull/1338#issuecomment-925008371
and https://github.com/glimmerjs/glimmer-vm/pull/1338#issuecomment-925017661

### CODE REVIEW

**Comment by chriskrycho** [comment]
If you rebase, I pushed updates over on #1338 which you should be able to take advantage of (it'll fix CI, for example).

**Comment by chriskrycho** [comment]
Also, ping me once this is green in CI and we'll get a version running against our app and see what we see!

**Comment by lifeart** [comment]
@chriskrycho ping

**Comment by chriskrycho** [comment]
@lifeart thank you – we're testing it now and will share results once we have them. 😅

**Comment by chriskrycho** [comment]
Okay, ran this against our app and: at least we have a good way of testing these kinds of things! Unfortunately, it looks like this makes things a bit worse across the board: it increases RSS, Heap Total, Heap Used, and Total Time.

Was worth a shot, though!

## Baseline (Ember 3.24, Glimmer 0.65)

| Build Type |   RSS   | Heap Total | Heap Used | External | Array Buffers |      Total Time      |
| ---------- | ------- | ---------- | --------- | -------- | ------------- | -------------------- |
| Cold Build | 9.90 GB | 2.72 GB    | 2.69 GB   | 71.20 MB | 66.16 MB      | 340204ms             |
| Warm Build | 2.62 GB | 2.42 GB    | 2.38 GB   | 73.95 MB | 68.84 MB      | 169507.66666666666ms |

## Current Glimmer VM `master`

This includes #1335 and #1338.

| Build Type |   RSS    | Heap Total | Heap Used | External | Array Buffers |      Total Time      |
| ---------- | -------- | ---------- | --------- | -------- | ------------- | -------------------- |
| Cold Build | 10.12 GB | 2.78 GB    | 2.74 GB   | 83.23 MB | 73.75 MB      | 358221ms             |
| Warm Build | 2.64 GB  | 2.44 GB    | 2.40 GB   | 70.89 MB | 65.92 MB      | 167512.66666666666ms |

## With this PR

| Build Type |   RSS    | Heap Total | Heap Used | External | Array Buffers |     Total Time      |
| ---------- | -------- | ---------- | --------- | -------- | ------------- | ------------------- |
| Cold Build | 10.59 GB | 3.17 GB    | 3.13 GB   | 71.14 MB | 65.78 MB      | 369038.3333333333ms |
| Warm Build | 2.64 GB  | 2.44 GB    | 2.40 GB   | 80.80 MB | 76.12 MB      | 168362ms            |

**Comment by lifeart** [comment]
Wow, thanks for testing it!

**Pull request closed without merging**
