### PR TITLE
[wip] trying to append items in list using fragment

### PR DESCRIPTION
**Pull request by lifeart**
Trying to get perf values for https://github.com/glimmerjs/glimmer-vm/issues/950

Mr created to get tracerbench results

upd:

looks like current benchmark not cover "append items to already rendered list of items", and perf-improvements should be related to this behavour

### CODE REVIEW

**Comment by vlascik** [comment]
Maybe you could try to benchmark it with https://github.com/krausest/js-framework-benchmark ? Ember's create row results have been an embarrassment there for years.

**Comment by NullVoxPopuli** [comment]
Is this still worth pursuing?

**Comment by lifeart** [comment]
@NullVoxPopuli I confused on adding "append" benchmark example, I need time or hep here

**Comment by wagenet** [comment]
It looks like this PR is stalled and since it's still in draft I'm going to go ahead and close it. If you do want to pick it up we'd be happy to do what we can to get it over the finish line.

**Comment by NullVoxPopuli** [comment]
There's also been recentist research written somewhere that fragments now slow things down a smidge

**Pull request closed without merging**
