### PR TITLE
Start fleshing out the precompiler docs

### PR DESCRIPTION
**Pull request by smfoote**

### CODE REVIEW

**Comment by wycats** [comment]
@smfoote what do you think about including some code snippets illustrating which APIs are in use?

**Comment by smfoote** [comment]
@wycats  I think that makes sense. Are you thinking the APIs used during precompilation (like `preprocess`, `TemplateCompiler.compile`, etc.) or the APIs that _call_ preprocess to get the precompilation started? Or both?

**Comment by wycats** [comment]
@smfoote Mostly I was thinking about the top-level APIs, but anything you think would help clarify the setup 😄

**Comment by wycats** [comment]
@smfoote Thanks! Keep 'em coming!

**Pull request merged**
