### PR TITLE
Upgrade to TypeScript 4.0

### PR DESCRIPTION
**Pull request by wycats**
This also updates the eslint-typescript packages

TypeScript 4.0 invalidated the way that we were casting SimpleDOM to
browser DOM and vice versa. This commit changes our casting strategy so
that casts go through additional checks that accomodate TypeScript's new
stricter requirements.

In general, this was a good change: it adds some checks to the blind
casts we were making, and caught at least one genuine mistake in our
casts (casting a textarea to input).

However, these checks add some minor overhead and should be unnecessary
in production. This commit structures the casts so they can be stripped
out relatively easily in the future, and we should do so.

### CODE REVIEW

**Comment by rwjblue** [comment]
Looks like some linting failures (likely due to typescript-eslint changing around the camelcase rule).

**Comment by krisselden** [comment]
IE 11 is failing with "Error: cannot cast a SimpleElement into an BrowserElementUtils outside of a browser environment"

**Comment by wycats** [comment]
> IE 11 is failing with "Error: cannot cast a SimpleElement into an BrowserElementUtils outside of a browser environment"

Fix incoming.

**Comment by rwjblue** [comment]
Once we get the linting failures fixed up, I'll work on ensuring the `cast` infrastructure is not used in production builds. At the moment, this introduces a ~ 1% performance regression (and I think we can fix that fairly easily with stripping out the type assertion related code).

**Comment by rwjblue** [comment]
Just pushed two changes: 

* Move cast into @glimmer/util
* Ensure `cast` is stripped in production builds

After those two tweaks, I confirmed that `cast` was indeed stripped when doing `ember build -prod`.

**Comment by rwjblue** [comment]
Just rebased to pull in the changes to #1156 so the PerformanceCheck CI job can run properly.

**Comment by rwjblue** [comment]
FYI - Labeled as `breaking` (to be safe)...

**Comment by wycats** [comment]
@rwjblue thanks for doing the heavy lifting!

**Pull request merged**
