### PR TITLE
remove assertion for now

### PR DESCRIPTION
**Pull request by stefanpenner**
re: #484 and https://github.com/emberjs/ember.js/issues/15255

### CODE REVIEW

**Comment by rwjblue** [comment]
The build is failing due to pre-existing type errors.  I suggest that we merge and manually release 😭.

Any objections?

**Comment by stefanpenner** [comment]
> Any objections?

no objections... unless @tomdale wants to fix :trollface:

**Comment by stefanpenner** [comment]
I'll go manually edit the tarball for release

**Comment by stefanpenner** [comment]
@rwjblue http://static.iamstef.net/glimmer-vm/package.tgz should be the tweaked package.tgz But requires someone else to sanity check me.

**Comment by rwjblue** [comment]
@stefanpenner the `package.json` version of that tarball is 0.23.0-alpha.1, but I would expect it to be 0.22.2.  Did you start from the 0.22.1 tarball or 0.23.0-alpha.1?

**Comment by stefanpenner** [comment]
good call, updating

**Comment by stefanpenner** [comment]
I just mutated this one ->`npm info glimmer-engine --json | jq -r '.dist.tarball'` i should grab something else.

**Comment by stefanpenner** [comment]
http://static.iamstef.net/glimmer-runtime/package.tgz is the right thing now I believe

**Pull request merged**
